# Generated by Django 2.0.6 on 2018-06-05 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
