# Generated by Django 2.0.6 on 2018-06-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountmodel',
            old_name='token',
            new_name='active_token',
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='password_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
