# Generated by Django 2.0.6 on 2018-06-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
